#!/usr/bin/env python3
"""Compare hologram intermediate node outputs against ORT intermediates.

Reads hologram dumps from /tmp/hologram_intermediates/ (generated by the
tinyllama_node_inspector Rust test) and ORT intermediates from
/tmp/ort_intermediates_seq{N}.npz (generated by ort_intermediates.py).

Reports the first node where hologram diverges from ORT, with detailed
diagnostics for debugging.

Usage:
  1. python3 scripts/ort_intermediates.py 5
  2. ORT_STRATEGY=system cargo test -p hologram-ai-conformance \
       --features "conformance,profile" --test exec_conformance \
       -- --ignored tinyllama_node_inspector --nocapture
  3. python3 scripts/compare_node_by_node.py
"""
import os
import sys
import numpy as np
from pathlib import Path

HOLO_DIR = Path("/tmp/hologram_intermediates")
ATOL = 1e-3
RTOL = 1e-2

def load_hologram_intermediates():
    """Load hologram node dumps from binary files."""
    nodes = {}
    for f in sorted(HOLO_DIR.glob("*.f32")):
        # Filename: {idx:05}_{name}.f32
        parts = f.stem.split("_", 1)
        idx = int(parts[0])
        name = parts[1] if len(parts) > 1 else "?"
        data = np.fromfile(f, dtype=np.float32)

        # Try to load shape file.
        shape_file = f.with_suffix(".shape")
        shape = None
        if shape_file.exists():
            shape_str = shape_file.read_text().strip()
            if shape_str:
                shape = tuple(int(d) for d in shape_str.split(","))
                if np.prod(shape) == len(data):
                    data = data.reshape(shape)

        nodes[name] = {"idx": idx, "data": data, "shape": shape}
    return nodes

def load_ort_intermediates(seq):
    """Load ORT intermediates from npz."""
    npz_path = f"/tmp/ort_intermediates_seq{seq}.npz"
    if not os.path.exists(npz_path):
        print(f"ERROR: ORT intermediates not found at {npz_path}")
        print(f"Run: python3 scripts/ort_intermediates.py {seq}")
        sys.exit(1)

    npz = np.load(npz_path)
    return {name: npz[name] for name in npz.files}

def compare_tensors(holo, ort, name):
    """Compare two tensors and return (passed, details)."""
    if holo.size == 0 or ort.size == 0:
        return True, "empty"

    h = holo.flatten()
    o = ort.flatten()

    # Size mismatch.
    if h.size != o.size:
        return False, f"size mismatch: holo={h.size} ort={o.size} (holo_shape={holo.shape} ort_shape={ort.shape})"

    # NaN/Inf check.
    h_nan = np.isnan(h).sum()
    o_nan = np.isnan(o).sum()
    h_inf = np.isinf(h).sum()
    o_inf = np.isinf(o).sum()

    if h_nan > 0 and o_nan == 0:
        return False, f"holo has {h_nan} NaN values, ORT has none"
    if h_inf > 0 and o_inf == 0:
        return False, f"holo has {h_inf} Inf values, ORT has none"

    # Value comparison.
    abs_diff = np.abs(h - o)
    max_abs = np.max(abs_diff)

    # Relative tolerance.
    denominator = np.maximum(np.abs(o), 1e-8)
    rel_diff = abs_diff / denominator
    max_rel = np.max(rel_diff)

    passed = max_abs <= ATOL or max_rel <= RTOL

    # Cosine similarity for additional insight.
    h_norm = np.linalg.norm(h)
    o_norm = np.linalg.norm(o)
    if h_norm > 0 and o_norm > 0:
        cosine = np.dot(h, o) / (h_norm * o_norm)
    else:
        cosine = 0.0

    details = (
        f"max_abs_diff={max_abs:.6f} max_rel_diff={max_rel:.6f} "
        f"cosine={cosine:.6f} "
        f"holo_range=[{h.min():.4f}, {h.max():.4f}] "
        f"ort_range=[{o.min():.4f}, {o.max():.4f}]"
    )

    return passed, details

def main():
    # Detect seq from index.tsv.
    index_file = HOLO_DIR / "index.tsv"
    if not index_file.exists():
        print(f"ERROR: No hologram intermediates found at {HOLO_DIR}")
        print("Run the tinyllama_node_inspector test first.")
        sys.exit(1)

    seq = 5  # default
    for line in index_file.read_text().splitlines():
        if line.startswith("seq="):
            seq = int(line.split("=")[1])
            break

    print(f"=== Node-by-node comparison (seq={seq}) ===\n")

    holo_nodes = load_hologram_intermediates()
    ort_nodes = load_ort_intermediates(seq)

    print(f"Hologram: {len(holo_nodes)} nodes")
    print(f"ORT:      {len(ort_nodes)} tensors\n")

    # Match by ONNX tensor name.
    matched = 0
    passed = 0
    failed = 0
    missing_in_ort = 0
    first_fail = None

    # Sort by hologram node index for topological order.
    sorted_holo = sorted(holo_nodes.items(), key=lambda x: x[1]["idx"])

    for name, hinfo in sorted_holo:
        if name == "?" or name.startswith("?"):
            continue

        if name not in ort_nodes:
            missing_in_ort += 1
            continue

        matched += 1
        ort_data = ort_nodes[name]
        holo_data = hinfo["data"]

        ok, details = compare_tensors(holo_data, ort_data, name)

        if ok:
            passed += 1
            # Only print first few passes.
            if passed <= 10:
                print(f"  PASS  node {hinfo['idx']:5d}  {name:40s}  {details}")
        else:
            failed += 1
            status = "FAIL"
            if first_fail is None:
                first_fail = (name, hinfo["idx"], details)
                status = "FAIL*"  # Mark first failure
            print(f"  {status} node {hinfo['idx']:5d}  {name:40s}  {details}")

            # For the first failure, print detailed comparison.
            if failed == 1:
                h = holo_data.flatten()
                o = ort_data.flatten()
                n = min(10, len(h), len(o))
                print(f"         holo first {n}: {h[:n]}")
                print(f"         ort  first {n}: {o[:n]}")
                if len(h) > 10:
                    print(f"         holo last  10: {h[-10:]}")
                    print(f"         ort  last  10: {o[-10:]}")

    # Summary.
    if passed > 10:
        print(f"  ... ({passed - 10} more passing nodes)")

    print(f"\n=== Summary ===")
    print(f"  Matched: {matched}")
    print(f"  Passed:  {passed}")
    print(f"  Failed:  {failed}")
    print(f"  Missing in ORT: {missing_in_ort}")

    if first_fail:
        name, idx, details = first_fail
        print(f"\n  FIRST DIVERGENCE: node {idx} '{name}'")
        print(f"    {details}")

        # Print the node's hologram predecessors to help trace the issue.
        print(f"\n  To investigate, check this node's inputs in the compiled graph.")
        print(f"  Look at nodes with idx < {idx} that feed into it.")
    else:
        print(f"\n  All nodes match within tolerance!")

if __name__ == "__main__":
    main()
